"""TransFusion-style anomaly detection baseline (per-class trainer + inferer).

A faithful re-implementation of the core ideas of TransFusion (Fucka et al.,
ECCV 2024 — github.com/MaticFuc/ECCV_TransFusion) adapted to match the I/O
contract of the v6 stacker. Outputs:

  - submission.csv             (q8rle-encoded test predictions)
  - local_predictions.npz      (val predictions + GT masks, for stacking)
  - run_log.txt                (training + inference log)

Key ideas (paraphrased from the paper):
  1. Synthetic anomalies are generated by alpha-blending textures from
     OTHER classes into normal images (no DTD dependency).
  2. A "transparency-based" forward process: at timestep t ∈ [0, T], the
     anomalous region is t/T transparent, so x_t = (1 - α(t)·M)·x_0 + α(t)·M·A.
  3. A U-Net with sinusoidal-time conditioning predicts BOTH (a) the anomaly
     mask at the current transparency level, and (b) the reconstructed normal.
  4. At inference, we run the network at a small set of timesteps and average
     the predicted masks. This is the multi-step inference TransFusion uses,
     simplified to a fixed schedule for predictable cost on a 4090.

Memory budget: ~12 GB VRAM at input 384, batch 8, ~30M params.
Per-class training time on a 4090: ~3 hours for 50k iters.

This script is designed to be a *drop-in* sibling of patchcore_baseline_v2.py
and fastflow_baseline.py. After it runs, splice_for_stacker.py merges its
class_03/class_07 predictions into a base method to produce a 16th stacker
column that doesn't break alignment.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import random
import sys
import time
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from scipy import ndimage as ndi
from torch.utils.data import DataLoader, Dataset


# ─────────────────────────────────────────────────────────────────────────────
# Tee logger (same convention as the rest of the pipeline)
# ─────────────────────────────────────────────────────────────────────────────
class Tee:
    def __init__(self, *streams):
        self.streams = streams

    def write(self, s):
        for st in self.streams: st.write(s); st.flush()

    def flush(self):
        for st in self.streams: st.flush()


@contextmanager
def tee_to(path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    f = open(path, "w", encoding="utf-8")
    old = sys.stdout
    sys.stdout = Tee(old, f)
    try:
        yield
    finally:
        sys.stdout = old;
        f.close()


def hr(t, c="="): print(f"\n{c * 78}\n  {t}\n{c * 78}")


# ─────────────────────────────────────────────────────────────────────────────
# q8rle codec — matches the format the stacker expects in submission.csv
# ─────────────────────────────────────────────────────────────────────────────
def float_matrix_to_q8rle(x: np.ndarray) -> str:
    q = np.clip(np.rint(np.asarray(x, dtype=np.float32) * 255),
                0, 255).astype(np.uint8)
    h, w = q.shape
    flat = q.T.reshape(-1)
    if flat.size == 0: return f"q8rle {h} {w}"
    cuts = np.flatnonzero(flat[1:] != flat[:-1]) + 1
    starts = np.r_[0, cuts];
    ends = np.r_[cuts, flat.size]
    parts = ["q8rle", str(h), str(w)]
    for v, n in zip(flat[starts], ends - starts):
        parts += [str(int(v)), str(int(n))]
    return " ".join(parts)


# ─────────────────────────────────────────────────────────────────────────────
# Dataset
# ─────────────────────────────────────────────────────────────────────────────
IMG_EXTS = {".png", ".jpg", ".jpeg", ".bmp", ".tiff", ".webp"}


def list_images(d: Path) -> list[Path]:
    if not d.exists(): return []
    return sorted([p for p in d.rglob("*")
                   if p.is_file() and p.suffix.lower() in IMG_EXTS])


def load_image(path: Path, size: int) -> np.ndarray:
    """Load → resize → [0,1] float32 RGB, shape (3, H, W)."""
    img = Image.open(path).convert("RGB")
    img = img.resize((size, size), Image.BILINEAR)
    arr = np.asarray(img, dtype=np.float32) / 255.0
    return arr.transpose(2, 0, 1)  # CHW


def load_mask(path: Path, size: int) -> np.ndarray:
    """Load mask → resize NN → uint8 (H, W), 1 = anomaly."""
    if not path.exists():
        return np.zeros((size, size), dtype=np.uint8)
    img = Image.open(path).convert("L")
    img = img.resize((size, size), Image.NEAREST)
    arr = np.asarray(img, dtype=np.uint8)
    return (arr > 0).astype(np.uint8)


def find_mask_for(image_path: Path, data_root: Path,
                  class_dir: Path, anomaly_type: str) -> Path:
    """Locate the GT mask file corresponding to an anomalous train image."""
    rel = image_path.relative_to(class_dir / "train" / anomaly_type)
    return class_dir / "ground_truth_train" / anomaly_type / rel


class NormalDataset(Dataset):
    """Returns normal training images in [0,1] CHW float32."""

    def __init__(self, paths: list[Path], size: int, aug: bool = True):
        self.paths = paths;
        self.size = size;
        self.aug = aug

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, i):
        x = load_image(self.paths[i], self.size)
        if self.aug:
            # h-flip
            if random.random() < 0.5: x = x[:, :, ::-1].copy()
            # small rotation (90/180/270 if you like — kept off; gear/pistachio
            # are roughly rotation-invariant but pistachio shells have a "right
            # side up" we shouldn't break.)
        return torch.from_numpy(x)


# ─────────────────────────────────────────────────────────────────────────────
# Synthetic anomaly generator
# ─────────────────────────────────────────────────────────────────────────────
def perlin_like_mask(H: int, W: int,
                     scale_min: int = 6, scale_max: int = 24,
                     threshold_pct: tuple[float, float] = (70.0, 90.0),
                     rng: np.random.Generator | None = None) -> np.ndarray:
    """Generate a binary blob mask with low-frequency structure. Output (H, W)
    uint8 with values {0, 1}. Used as the anomaly footprint."""
    rng = rng or np.random.default_rng()
    scale = int(rng.integers(scale_min, scale_max + 1))
    low = rng.random((scale, scale)).astype(np.float32)
    smooth = ndi.zoom(low, (H / scale, W / scale), order=1)
    if smooth.shape != (H, W):
        # numerical rounding correction
        smooth = smooth[:H, :W]
        if smooth.shape != (H, W):
            pad_h = H - smooth.shape[0];
            pad_w = W - smooth.shape[1]
            smooth = np.pad(smooth, ((0, pad_h), (0, pad_w)), mode="edge")
    t = float(rng.uniform(threshold_pct[0], threshold_pct[1]))
    threshold = float(np.percentile(smooth, t))
    return (smooth > threshold).astype(np.uint8)


def small_blob_mask(H: int, W: int,
                    n_blobs: int = 1,
                    min_radius: int = 4, max_radius: int = 20,
                    rng: np.random.Generator | None = None) -> np.ndarray:
    """Generate small focal blobs (better match for scratches / pits)."""
    rng = rng or np.random.default_rng()
    mask = np.zeros((H, W), dtype=np.uint8)
    yy, xx = np.indices((H, W))
    for _ in range(n_blobs):
        r = int(rng.integers(min_radius, max_radius + 1))
        cy = int(rng.integers(r, H - r))
        cx = int(rng.integers(r, W - r))
        # ellipse with random aspect ratio (for scratches)
        ar = float(rng.uniform(0.3, 1.0))
        if rng.random() < 0.5: ar = 1.0 / ar
        rad_y = max(2, int(r * ar));
        rad_x = max(2, int(r / ar))
        dist = ((yy - cy) / rad_y) ** 2 + ((xx - cx) / rad_x) ** 2
        mask |= (dist <= 1.0).astype(np.uint8)
    return mask


class TexturePool:
    """Pool of texture patches sampled from OTHER classes' train images.
    Avoids the DTD download by using domain-adjacent textures."""

    def __init__(self, paths: list[Path], size: int, pool_size: int = 256,
                 seed: int = 0):
        self.size = size
        rng = np.random.default_rng(seed)
        idxs = rng.choice(len(paths), size=min(pool_size, len(paths)),
                          replace=False) if paths else np.array([], dtype=int)
        self.images: list[np.ndarray] = []
        for i in idxs:
            try:
                arr = load_image(paths[int(i)], size)
                self.images.append(arr)
            except Exception:
                continue
        print(f"  TexturePool: loaded {len(self.images)} texture images "
              f"from {len(paths)} candidate paths")

    def sample(self, rng: np.random.Generator) -> np.ndarray:
        """Return (3, H, W) texture in [0, 1]."""
        if not self.images:
            # fallback: random noise
            return rng.random((3, self.size, self.size)).astype(np.float32)
        idx = int(rng.integers(0, len(self.images)))
        t = self.images[idx].copy()
        # color jitter
        for c in range(3):
            t[c] = np.clip(t[c] * rng.uniform(0.7, 1.3), 0.0, 1.0)
        # h-flip
        if rng.random() < 0.5: t = t[:, :, ::-1].copy()
        # v-flip
        if rng.random() < 0.5: t = t[:, ::-1, :].copy()
        return t


def synthesize_anomalous_batch(x_normal: torch.Tensor,
                               texture_pool: TexturePool,
                               rng: np.random.Generator,
                               blob_mode_prob: float = 0.5):
    """Build a batch of (x_anomaly, M_true) given x_normal.

    Returns:
      x_anomaly: (B, 3, H, W) — anomalous version of each image
      M_true:    (B, 1, H, W) — binary mask (1 = anomaly)
      beta:      (B, 1, 1, 1) — per-sample blend strength
    """
    B, C, H, W = x_normal.shape
    device = x_normal.device
    M = np.zeros((B, 1, H, W), dtype=np.float32)
    T = np.zeros((B, 3, H, W), dtype=np.float32)
    for i in range(B):
        # Half blob-style (focal, good for scratches/pits), half perlin-style
        # (broader, good for stains/discoloration). Class_03 and class_07 each
        # need both; mixing them in training gives the model exposure.
        if rng.random() < blob_mode_prob:
            n_blobs = int(rng.integers(1, 4))
            m = small_blob_mask(H, W, n_blobs=n_blobs, rng=rng)
        else:
            m = perlin_like_mask(H, W, rng=rng)
        M[i, 0] = m.astype(np.float32)
        T[i] = texture_pool.sample(rng)
    M_t = torch.from_numpy(M).to(device)
    T_t = torch.from_numpy(T).to(device)
    # Per-sample blend strength β ∈ [0.4, 0.95]: high enough that anomalies
    # actually differ from normal, low enough that some defects look subtle.
    beta = torch.from_numpy(
        rng.uniform(0.4, 0.95, size=(B, 1, 1, 1)).astype(np.float32)
    ).to(device)
    # Final anomalous image: where M=1, blend in the texture by β
    x_anomaly = x_normal * (1.0 - beta * M_t) + T_t * (beta * M_t)
    return x_anomaly, M_t, beta


# ─────────────────────────────────────────────────────────────────────────────
# U-Net with sinusoidal time embedding (≈25M params at base=64)
# ─────────────────────────────────────────────────────────────────────────────
class SinusoidalTimeEmbed(nn.Module):
    def __init__(self, dim: int):
        super().__init__()
        self.dim = dim

    def forward(self, t: torch.Tensor) -> torch.Tensor:
        # t: (B,) float in [0, 1] — already normalized
        half = self.dim // 2
        freqs = torch.exp(
            -math.log(10000.0)
            * torch.arange(half, device=t.device, dtype=torch.float32) / half
        )
        ang = t[:, None].float() * freqs[None, :]
        emb = torch.cat([ang.sin(), ang.cos()], dim=-1)
        if self.dim % 2 == 1:
            emb = F.pad(emb, (0, 1))
        return emb


class ResBlock(nn.Module):
    def __init__(self, in_ch, out_ch, time_dim):
        super().__init__()
        self.norm1 = nn.GroupNorm(8, in_ch)
        self.conv1 = nn.Conv2d(in_ch, out_ch, 3, padding=1)
        self.time_proj = nn.Linear(time_dim, out_ch)
        self.norm2 = nn.GroupNorm(8, out_ch)
        self.conv2 = nn.Conv2d(out_ch, out_ch, 3, padding=1)
        self.skip = (nn.Conv2d(in_ch, out_ch, 1) if in_ch != out_ch
                     else nn.Identity())

    def forward(self, x, t_emb):
        h = self.conv1(F.silu(self.norm1(x)))
        h = h + self.time_proj(F.silu(t_emb))[:, :, None, None]
        h = self.conv2(F.silu(self.norm2(h)))
        return h + self.skip(x)


class Downsample(nn.Module):
    def __init__(self, ch):
        super().__init__()
        self.conv = nn.Conv2d(ch, ch, 3, stride=2, padding=1)

    def forward(self, x): return self.conv(x)


class Upsample(nn.Module):
    def __init__(self, ch):
        super().__init__()
        self.conv = nn.Conv2d(ch, ch, 3, padding=1)

    def forward(self, x):
        x = F.interpolate(x, scale_factor=2, mode="nearest")
        return self.conv(x)


class TransFusionUNet(nn.Module):
    """U-Net that predicts (a) anomaly mask + (b) reconstructed normal image
    from a noisy/anomalous input at a given transparency level t.

    Input:  x_t (B, 3, H, W) + time t (B,)
    Output: out (B, 4, H, W), where:
              channels 0:1 = anomaly mask logits
              channels 1:4 = reconstructed normal (in [0, 1] after sigmoid)
    """

    def __init__(self, base: int = 64, time_dim: int = 256, in_ch: int = 3,
                 out_ch: int = 4):
        super().__init__()
        self.time_embed = nn.Sequential(
            SinusoidalTimeEmbed(time_dim),
            nn.Linear(time_dim, time_dim),
            nn.SiLU(),
            nn.Linear(time_dim, time_dim),
        )
        widths = [base, base * 2, base * 4, base * 8]
        # Stem
        self.stem = nn.Conv2d(in_ch, widths[0], 3, padding=1)
        # Encoder
        self.down1 = nn.ModuleList([
            ResBlock(widths[0], widths[0], time_dim),
            ResBlock(widths[0], widths[0], time_dim)])
        self.ds1 = Downsample(widths[0])
        self.down2 = nn.ModuleList([
            ResBlock(widths[0], widths[1], time_dim),
            ResBlock(widths[1], widths[1], time_dim)])
        self.ds2 = Downsample(widths[1])
        self.down3 = nn.ModuleList([
            ResBlock(widths[1], widths[2], time_dim),
            ResBlock(widths[2], widths[2], time_dim)])
        self.ds3 = Downsample(widths[2])
        # Bottleneck
        self.mid1 = ResBlock(widths[2], widths[3], time_dim)
        self.mid2 = ResBlock(widths[3], widths[3], time_dim)
        # Decoder
        self.us3 = Upsample(widths[3])
        self.up3 = nn.ModuleList([
            ResBlock(widths[3] + widths[2], widths[2], time_dim),
            ResBlock(widths[2], widths[2], time_dim)])
        self.us2 = Upsample(widths[2])
        self.up2 = nn.ModuleList([
            ResBlock(widths[2] + widths[1], widths[1], time_dim),
            ResBlock(widths[1], widths[1], time_dim)])
        self.us1 = Upsample(widths[1])
        self.up1 = nn.ModuleList([
            ResBlock(widths[1] + widths[0], widths[0], time_dim),
            ResBlock(widths[0], widths[0], time_dim)])
        # Head
        self.head_norm = nn.GroupNorm(8, widths[0])
        self.head = nn.Conv2d(widths[0], out_ch, 3, padding=1)

    def forward(self, x: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        t_emb = self.time_embed(t)
        h0 = self.stem(x)
        h1 = h0
        for b in self.down1: h1 = b(h1, t_emb)
        d1 = self.ds1(h1)
        h2 = d1
        for b in self.down2: h2 = b(h2, t_emb)
        d2 = self.ds2(h2)
        h3 = d2
        for b in self.down3: h3 = b(h3, t_emb)
        d3 = self.ds3(h3)
        m = self.mid1(d3, t_emb);
        m = self.mid2(m, t_emb)
        u3 = self.us3(m);
        u3 = torch.cat([u3, h3], dim=1)
        for b in self.up3: u3 = b(u3, t_emb)
        u2 = self.us2(u3);
        u2 = torch.cat([u2, h2], dim=1)
        for b in self.up2: u2 = b(u2, t_emb)
        u1 = self.us1(u2);
        u1 = torch.cat([u1, h1], dim=1)
        for b in self.up1: u1 = b(u1, t_emb)
        return self.head(F.silu(self.head_norm(u1)))


def split_outputs(out: torch.Tensor):
    """out: (B, 4, H, W) → (mask_logit (B,1,H,W), recon (B,3,H,W) in [0,1])"""
    mask_logit = out[:, :1]
    recon = torch.sigmoid(out[:, 1:4])
    return mask_logit, recon


# ─────────────────────────────────────────────────────────────────────────────
# Losses
# ─────────────────────────────────────────────────────────────────────────────
def focal_loss(logits: torch.Tensor, target: torch.Tensor,
               alpha: float = 0.75, gamma: float = 2.0) -> torch.Tensor:
    """Binary focal loss on per-pixel logits. target ∈ {0, 1}."""
    p = torch.sigmoid(logits)
    bce = F.binary_cross_entropy_with_logits(logits, target, reduction="none")
    p_t = target * p + (1 - target) * (1 - p)
    alpha_t = target * alpha + (1 - target) * (1 - alpha)
    return (alpha_t * (1 - p_t).pow(gamma) * bce).mean()


# ─────────────────────────────────────────────────────────────────────────────
# Training loop
# ─────────────────────────────────────────────────────────────────────────────
@dataclass
class TrainCfg:
    iters: int = 50_000
    batch_size: int = 8
    lr: float = 2e-4
    weight_decay: float = 1e-4
    T_max: int = 20
    blob_mode_prob: float = 0.5
    log_every: int = 200
    ckpt_every: int = 5_000


def train_one_class(model: TransFusionUNet,
                    normal_paths: list[Path],
                    texture_pool: TexturePool,
                    cfg: TrainCfg,
                    size: int,
                    device: torch.device,
                    seed: int,
                    out_dir: Path) -> dict:
    """Train per-class. Returns a dict of final-step metrics."""
    rng = np.random.default_rng(seed)
    torch.manual_seed(seed)

    ds = NormalDataset(normal_paths, size=size, aug=True)
    if len(ds) == 0:
        raise RuntimeError("no normal training images found")
    loader = DataLoader(ds, batch_size=cfg.batch_size, shuffle=True,
                        num_workers=2, pin_memory=True, drop_last=True,
                        persistent_workers=True)
    print(f"  Dataset: {len(ds)} normals; batch {cfg.batch_size}; "
          f"input {size}x{size}")

    opt = torch.optim.AdamW(model.parameters(), lr=cfg.lr,
                            weight_decay=cfg.weight_decay)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(
        opt, T_max=cfg.iters, eta_min=cfg.lr * 0.01)

    scaler = torch.cuda.amp.GradScaler()
    model.train()
    it = 0;
    t0 = time.time()
    running = {"mask": 0.0, "recon": 0.0, "total": 0.0}
    last_metrics: dict = {}
    while it < cfg.iters:
        for x_normal in loader:
            if it >= cfg.iters: break
            x_normal = x_normal.to(device, non_blocking=True)
            B = x_normal.shape[0]
            with torch.no_grad():
                x_anom, M_true, _beta = synthesize_anomalous_batch(
                    x_normal, texture_pool, rng,
                    blob_mode_prob=cfg.blob_mode_prob)
            # Sample transparency level t ~ Uniform[1, T_max] / T_max
            t_int = torch.randint(1, cfg.T_max + 1, (B,), device=device)
            t = t_int.float() / cfg.T_max  # ∈ (0, 1]
            # Forward "diffusion": linearly interpolate normal → anomaly
            x_t = (1.0 - t.view(B, 1, 1, 1)) * x_normal \
                  + t.view(B, 1, 1, 1) * x_anom

            opt.zero_grad(set_to_none=True)
            with torch.cuda.amp.autocast(dtype=torch.float16):
                out = model(x_t, t)
                mask_logit, recon = split_outputs(out)
                # Mask target is M_true scaled by t (when t≈0 there's no
                # anomaly to find; this avoids forcing the model to predict
                # phantom masks at t=0).
                target_mask = M_true * (t.view(B, 1, 1, 1) > 0.05).float()
                l_mask = focal_loss(mask_logit, target_mask,
                                    alpha=0.75, gamma=2.0)
                l_recon = F.l1_loss(recon, x_normal)
                loss = l_mask + 0.5 * l_recon
            scaler.scale(loss).backward()
            scaler.unscale_(opt)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(opt);
            scaler.update();
            sched.step()

            running["mask"] += l_mask.item()
            running["recon"] += l_recon.item()
            running["total"] += loss.item()
            it += 1

            if it % cfg.log_every == 0:
                elapsed = time.time() - t0
                its_per_s = it / max(elapsed, 1e-3)
                eta = (cfg.iters - it) / max(its_per_s, 1e-3)
                avg = {k: v / cfg.log_every for k, v in running.items()}
                last_metrics = avg
                print(f"  iter {it:>6d}/{cfg.iters}  "
                      f"loss={avg['total']:.4f}  "
                      f"mask={avg['mask']:.4f}  recon={avg['recon']:.4f}  "
                      f"lr={sched.get_last_lr()[0]:.2e}  "
                      f"{its_per_s:.1f} it/s  ETA {eta / 60:.1f}m",
                      flush=True)
                running = {"mask": 0.0, "recon": 0.0, "total": 0.0}

            if cfg.ckpt_every > 0 and it % cfg.ckpt_every == 0:
                ck = out_dir / f"ckpt_iter{it:06d}.pt"
                torch.save({"model": model.state_dict(), "it": it,
                            "cfg": cfg.__dict__}, ck)
                print(f"  [ckpt] {ck.name}")
    final_ck = out_dir / "ckpt_final.pt"
    torch.save({"model": model.state_dict(), "it": it,
                "cfg": cfg.__dict__}, final_ck)
    print(f"  [ckpt] {final_ck.name}  (final, after {it} iters, "
          f"{(time.time() - t0) / 60:.1f}m)")
    return last_metrics


# ─────────────────────────────────────────────────────────────────────────────
# Inference
# ─────────────────────────────────────────────────────────────────────────────
@torch.no_grad()
def infer_one_image_batch(model: TransFusionUNet,
                          x: torch.Tensor,
                          T_max: int,
                          t_steps: tuple[int, ...] = (5, 10, 15, 20),
                          tta_hvflip: bool = True) -> torch.Tensor:
    """x: (B, 3, H, W). Returns (B, H, W) float anomaly score in [0, 1].

    We query the network at several transparency levels and average the
    predicted masks. This is a TTA-on-time strategy: at inference we don't
    know "how anomalous" the input is, so we hedge across multiple guesses.
    """
    B = x.shape[0];
    device = x.device
    accum = torch.zeros((B, 1, x.shape[2], x.shape[3]),
                        device=device, dtype=torch.float32)
    n = 0
    flips = [False, True] if tta_hvflip else [False]
    for flip in flips:
        x_in = torch.flip(x, dims=[3]) if flip else x
        for t_val in t_steps:
            t = torch.full((B,), t_val / T_max, device=device,
                           dtype=torch.float32)
            with torch.cuda.amp.autocast(dtype=torch.float16):
                out = model(x_in, t)
                mask_logit, _ = split_outputs(out)
                mask = torch.sigmoid(mask_logit.float())
            if flip: mask = torch.flip(mask, dims=[3])
            accum = accum + mask;
            n += 1
    return (accum / max(n, 1)).squeeze(1).clamp(0.0, 1.0)


def run_inference(model: TransFusionUNet,
                  image_paths: list[Path],
                  size: int,
                  device: torch.device,
                  T_max: int,
                  t_steps: tuple[int, ...],
                  tta_hvflip: bool,
                  batch_size: int = 8) -> np.ndarray:
    """Run inference on a list of images. Returns (N, H, W) float32 anomaly
    scores, where H=W=size."""
    model.eval()
    N = len(image_paths)
    out = np.empty((N, size, size), dtype=np.float32)
    bi = 0
    t0 = time.time()
    while bi < N:
        end = min(bi + batch_size, N)
        batch_imgs = [load_image(p, size) for p in image_paths[bi:end]]
        x = torch.from_numpy(np.stack(batch_imgs)).to(device,
                                                      non_blocking=True)
        scores = infer_one_image_batch(model, x, T_max=T_max,
                                       t_steps=t_steps,
                                       tta_hvflip=tta_hvflip)
        out[bi:end] = scores.cpu().numpy()
        if (end // batch_size) % 20 == 0:
            print(f"    inferred {end}/{N} ({time.time() - t0:.1f}s)",
                  flush=True)
        bi = end
    print(f"  inference done: {N} images in {time.time() - t0:.1f}s")
    return out


# ─────────────────────────────────────────────────────────────────────────────
# Main — per-class trainer + inferer
# ─────────────────────────────────────────────────────────────────────────────
def collect_anom_train_for_class(class_dir: Path) -> tuple[list[Path], list[str], list[Path]]:
    """Find anomalous train images (used as val) for a class. Returns
    (image_paths, anomaly_types_per_image, mask_paths)."""
    train_dir = class_dir / "train"
    if not train_dir.exists(): return [], [], []
    out_imgs, out_types, out_masks = [], [], []
    for sub in sorted(train_dir.iterdir()):
        if not sub.is_dir() or sub.name == "good": continue
        atype = sub.name
        imgs = list_images(sub)
        for img in imgs:
            mask = find_mask_for(img, class_dir.parent, class_dir, atype)
            out_imgs.append(img);
            out_types.append(atype);
            out_masks.append(mask)
    return out_imgs, out_types, out_masks


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data-root", type=Path, required=True,
                    help="dataset root, e.g. .../anomaly-detection/data")
    ap.add_argument("--classes", nargs="+", required=True,
                    help="class names to train, e.g. class_03 class_07")
    ap.add_argument("--input-size", type=int, default=384)
    ap.add_argument("--iters", type=int, default=50_000)
    ap.add_argument("--batch-size", type=int, default=8)
    ap.add_argument("--lr", type=float, default=2e-4)
    ap.add_argument("--T-max", type=int, default=20)
    ap.add_argument("--base-width", type=int, default=64)
    ap.add_argument("--tta-hvflip", action="store_true",
                    help="enable h-flip TTA at inference")
    ap.add_argument("--inference-t-steps", nargs="+", type=int,
                    default=[5, 10, 15, 20])
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--out-root", type=Path, required=True,
                    help="directory under which to create the run dir")
    ap.add_argument("--run-tag", default="transfusion_baseline")
    ap.add_argument("--texture-classes", nargs="*", default=None,
                    help="classes to sample synthetic-anomaly textures from "
                         "(default: all classes EXCEPT the one being trained)")
    args = ap.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type != "cuda":
        print("[WARN] CUDA not available; this will be very slow on CPU.")

    # One run dir per invocation, holds per-class sub-results
    ts = time.strftime("%Y%m%d-%H%M%S")
    cls_tag = "_".join(args.classes)
    run_hash = hashlib.sha1(
        f"{ts}|{cls_tag}|{args.input_size}|{args.iters}|{args.seed}".encode()
    ).hexdigest()[:6]
    run_name = (f"{ts}_transfusion_in{args.input_size}_{cls_tag}_"
                f"it{args.iters}_T{args.T_max}_{args.run_tag}_{run_hash}")
    run_dir = args.out_root / run_name
    run_dir.mkdir(parents=True, exist_ok=True)

    with tee_to(run_dir / "run_log.txt"):
        hr(f"TRANSFUSION — classes {args.classes}", "=")
        print(f"  data_root         : {args.data_root}")
        print(f"  input_size        : {args.input_size}")
        print(f"  iters             : {args.iters}")
        print(f"  batch_size        : {args.batch_size}")
        print(f"  T_max             : {args.T_max}")
        print(f"  base_width        : {args.base_width}")
        print(f"  tta_hvflip        : {args.tta_hvflip}")
        print(f"  inference_t_steps : {args.inference_t_steps}")
        print(f"  seed              : {args.seed}")
        print(f"  run_dir           : {run_dir}")

        # Per-class accumulators for the *final* local_predictions.npz
        # and submission.csv. We only cover args.classes; the splicer
        # will fill the rest from a base method.
        all_val_ids: list[str] = []
        all_val_classes: list[str] = []
        all_val_atypes: list[str] = []
        all_val_scores: list[np.ndarray] = []
        all_val_masks: list[np.ndarray] = []
        all_val_paths: list[str] = []
        all_test_rows: list[tuple[str, str]] = []  # (id, q8rle)

        per_class_summary: dict = {}

        for cls in args.classes:
            hr(f"CLASS {cls}", "=")
            cls_dir = args.data_root / cls
            if not cls_dir.exists():
                print(f"  [FATAL] {cls_dir} does not exist; skipping")
                continue

            # ── Normal training paths ────────────────────────────────────────
            normal_dir = cls_dir / "train" / "good"
            normal_paths = list_images(normal_dir)
            print(f"  normal images: {len(normal_paths)} (from {normal_dir})")
            if not normal_paths:
                print(f"  [FATAL] no good/ images for {cls}; skipping")
                continue

            # ── Texture pool from OTHER classes ──────────────────────────────
            tex_classes = (args.texture_classes if args.texture_classes
                           else [d.name for d in args.data_root.iterdir()
                                 if d.is_dir() and d.name.startswith("class_")
                                 and d.name != cls])
            tex_paths: list[Path] = []
            for tc in tex_classes:
                tex_paths.extend(list_images(args.data_root / tc / "train" / "good"))
            print(f"  texture pool source: {len(tex_classes)} classes, "
                  f"{len(tex_paths)} images")
            texture_pool = TexturePool(tex_paths, size=args.input_size,
                                       pool_size=256, seed=args.seed)

            # ── Model + train ────────────────────────────────────────────────
            model = TransFusionUNet(base=args.base_width).to(device)
            n_params = sum(p.numel() for p in model.parameters())
            print(f"  model params: {n_params / 1e6:.2f}M")
            cfg = TrainCfg(iters=args.iters, batch_size=args.batch_size,
                           lr=args.lr, T_max=args.T_max)
            cls_dir_out = run_dir / cls
            cls_dir_out.mkdir(parents=True, exist_ok=True)
            print(f"\n  ─── training {cls} ───")
            final_metrics = train_one_class(
                model, normal_paths, texture_pool, cfg,
                size=args.input_size, device=device, seed=args.seed,
                out_dir=cls_dir_out)

            # ── Inference on anomalous TRAIN (= our val set) ─────────────────
            print(f"\n  ─── inference on val (anomalous train) for {cls} ───")
            val_imgs, val_atypes, val_mask_paths = collect_anom_train_for_class(cls_dir)
            print(f"  val images: {len(val_imgs)}")
            val_scores = run_inference(
                model, val_imgs, size=args.input_size, device=device,
                T_max=args.T_max,
                t_steps=tuple(args.inference_t_steps),
                tta_hvflip=args.tta_hvflip)
            val_masks = np.stack(
                [load_mask(mp, args.input_size) for mp in val_mask_paths],
                axis=0).astype(np.uint8) if val_imgs else np.zeros(
                (0, args.input_size, args.input_size), dtype=np.uint8)
            for i, p in enumerate(val_imgs):
                # ID convention used by the rest of the pipeline:
                # filename stem (relative-path-aware)
                sid = p.stem
                all_val_ids.append(sid)
                all_val_classes.append(cls)
                all_val_atypes.append(val_atypes[i])
                all_val_paths.append(str(p))
            all_val_scores.append(val_scores)
            all_val_masks.append(val_masks)

            # Quick sanity AP on val
            try:
                from sklearn.metrics import average_precision_score
                y = val_masks.ravel()
                s = val_scores.ravel()
                if int(y.sum()) > 0:
                    ap = float(average_precision_score(y, s))
                    print(f"  val pooled pixel-AP for {cls}: {ap:.4f}")
                    per_class_summary[cls] = {"val_pooled_ap": ap,
                                              "n_val": len(val_imgs)}
            except Exception as e:
                print(f"  [warn] could not compute val AP: {e}")

            # ── Inference on test ────────────────────────────────────────────
            test_dir = cls_dir / "test"
            test_imgs = list_images(test_dir)
            print(f"\n  ─── inference on test for {cls} ({len(test_imgs)} images) ───")
            if test_imgs:
                test_scores = run_inference(
                    model, test_imgs, size=args.input_size, device=device,
                    T_max=args.T_max,
                    t_steps=tuple(args.inference_t_steps),
                    tta_hvflip=args.tta_hvflip)
                for i, p in enumerate(test_imgs):
                    sid = p.stem
                    all_test_rows.append((sid, float_matrix_to_q8rle(test_scores[i])))

            # Free GPU memory before the next class
            del model
            torch.cuda.empty_cache()

        # ── Write submission.csv (only target classes' rows) ────────────────
        sub_path = run_dir / "submission.csv"
        with open(sub_path, "w", newline="", encoding="utf-8") as f:
            w = csv.writer(f);
            w.writerow(["ID", "Label"])
            for sid, lbl in all_test_rows:
                w.writerow([sid, lbl])
        print(f"\nWrote {len(all_test_rows)} test rows -> {sub_path}")

        # ── Write local_predictions.npz (only target classes' rows) ─────────
        local_path = run_dir / "local_predictions.npz"
        if all_val_scores:
            np.savez_compressed(
                local_path,
                ids=np.array(all_val_ids, dtype=object),
                classes=np.array(all_val_classes, dtype=object),
                anomaly_types=np.array(all_val_atypes, dtype=object),
                scores=np.concatenate(all_val_scores, axis=0).astype(np.float32),
                masks=np.concatenate(all_val_masks, axis=0).astype(np.uint8),
                image_paths=np.array(all_val_paths, dtype=object),
            )
            print(f"Wrote val preds -> {local_path}")

        # ── Manifest ────────────────────────────────────────────────────────
        manifest = {
            "method_name": run_name,
            "model_family": "transfusion",
            "classes_covered": args.classes,
            "input_size": args.input_size,
            "T_max": args.T_max,
            "iters": args.iters,
            "batch_size": args.batch_size,
            "tta_hvflip": args.tta_hvflip,
            "inference_t_steps": list(args.inference_t_steps),
            "seed": args.seed,
            "per_class": per_class_summary,
        }
        with open(run_dir / "manifest.json", "w") as f:
            json.dump(manifest, f, indent=2, default=str)
        hr(f"DONE — {run_dir.name}", "=")


if __name__ == "__main__":
    main()